### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'wrapperEl' of null

### ISSUE THREAD

**Issue by whq920729** [cycdpo/swiper-animation#10]
![image](https://user-images.githubusercontent.com/19342174/61094717-dbb09f80-a482-11e9-9beb-26f4d817b2d4.png)
Firstly, thanks for your good plugin! Init the page, this bug is show, but animations features are working... so , this bug can be ignored? thanks!

**Comment by cycjimmy** [comment]
Pass a swiper instance into the `swiperAnimation.init()` function.
* See [https://github.com/cycdpo/swiper-animation#usage](https://github.com/cycdpo/swiper-animation#usage)

**Comment by cycjimmy** [comment]
I think I find the problem. 

```javascript
const swiperAnimation = new SwiperAnimation();
const mySwiper = new Swiper('.swiper-container', {
  on: {
    init: () => swiperAnimation.init(mySwiper).animate(),
    slideChange: () => swiperAnimation.init(mySwiper).animate()
  }
});
```
 
Run the code above. `mySwiper` is `undefined` when the swiper instance is initializing.
You can modify it to the following code to fix the problem.

```javascript
const swiperAnimation = new SwiperAnimation();
const mySwiper = new Swiper('.swiper-container', {
  on: {
    init: function () {
      swiperAnimation.init(this).animate();
    },
    
    // or: If you want to use the arrow function ...
    init: () => setTimeout(() => swiperAnimation.init(mySwiper).animate(), 0),
    ...
  }
});
```

**Comment by whq920729** [comment]
good！it works! thanks!
