### ISSUE TITLE
Promise Is Undefined in Internet Explorer 11

### ISSUE THREAD

**Issue by nselden** [cycdpo/swiper-animation#4]
Any idea what would cause the Internet Explorer console to generate this error? 

'Promise' is undefined

using Swiper 4.2.2

Let me know if you need anymore information. Thanks!

**Comment by nselden** [comment]
Found it. Internet Explorer does not natively support the Promise Library

as per this stackoverflow 

https://stackoverflow.com/questions/36831372/promise-is-undefined-in-ie

**Comment by cycjimmy** [comment]
Thank you for your issue. I have fixed it .
