### ISSUE TITLE
This will not work when loop is enabled

### ISSUE THREAD

**Issue by mrkenng** [cycdpo/swiper-animation#7]
Hi there! Thanks for this ! However, recently I found out that when using loop, this will not work anymore.

**Comment by cycjimmy** [comment]
:smile: Thanks for your issue, and I have fixed it in [v1.2.4](https://github.com/cycdpo/swiper-animation/releases/tag/v1.2.4).

If everything works, the issue will be closed after a week.

**Comment by mrkenng** [comment]
Sorry for the late reply! Just tested and it is working 👍👍👍 thanks!
