### ISSUE TITLE
Back animation

### ISSUE THREAD

**Issue by s5t5n** [cycdpo/swiper-animation#9]
Everything works fine, but there is no back animation. So if anyone want to animate an element - it works, but then the slide is changes, the animated element just DISSAPEARING, without "roll back animation function", if you know that i mean.

I've done this with a css:

```
.ANIMATED-ELEMENT {
  color: #fff;
  transition: all .1s cubic-bezier(0.215, 0.61, 0.355, 1) .1s;
  -webkit-transform: translate3d(-20%, 0, 0);
          transform: translate3d(-20%, 0, 0);
  opacity: 0;
}

.swiper-slide.swiper-slide-active .ANIMATED-ELEMENT {
  transition: all .5s cubic-bezier(0.215, 0.61, 0.355, 1) .5s;
  -webkit-transform: translate3d(0, 0, 0);
          transform: translate3d(0, 0, 0);
  opacity: 1;
}
```

So, as you can see, there will be a fast back animation, then the slide becomes UNactive and will lose his .swiper-slide-active class. Can you make IN animation and OUT animation?

**Comment by cycjimmy** [comment]
Adding "roll back animation" manually, then delaying to leave the slide.

**Comment by cycjimmy** [comment]
"Out animation" is already supported in v1.3.0.  
Try to use `data-swiper-out-animation` attribute on elements.

**Comment by s5t5n** [comment]
Great! Thanks.
